### ISSUE TITLE
Fix abisko.se biomass data: has NA cover values in even plots

### ISSUE THREAD

**Issue by carlos-arnillas** [nutnetadmin/nutnet-data-tracker#28] opened 2018-01-10 17:43 UTC
Hi
That happen in the comb-by-plot-clim-soil-diversity-04-Dec-2017.csv
Thanks!

Carlos Alberto # #

**Comment by nutnetadmin** [comment] 2018-01-19 16:30
Thank you Carlos! I will check it out.
Ashley

**Comment by nutnetadmin** [comment] 2018-01-19 16:31
Not a bug: Abisko measured biomass in 20 plots, but cover in only half of them.

**Comment by nutnetadmin** [comment] 2018-03-22 14:29
Carlos was right. Email from Andrew MacDougall:

Hi Ashley
We did the observational minimum of 10 plots per site
For each plot we did two 10 cm x 100 cm biomass strips, that is why there are 20 per site
Does that make sense?
Let me know
Andrew

**Comment by carlos-arnillas** [comment] 2018-03-22 17:22
Hi Andrew, Ashley,
Andrew, it makes, but how should the strips be combined to make them most
similar to a normal experimental setting?
for instance, should biomass strips 1 and 2 be combined (so that they
relate to the 2 strips per plot in an experimental setting)?
also, were biomass strips located nearby the coverage plot? (like in < 2m
range as is the experimental setting?) if so, should strips 1 and 2
(assuming that's the right grouping) be linked to cover in plot 1?
Thanks again!

Carlos Alberto

**Comment by nutnetadmin** [comment] 2018-03-26 16:13
Updated plot numbering and all associated records (biomass, cover, par) in script
import-absiskojuare-2016-fix-plot.sql

Moving on to update records for kark.se if needed

**Comment by nutnetadmin** [comment] 2018-04-06 14:45
Need to fix this for the soil data as well...records seem to not be linking up now.

**Comment by nutnetadmin** [comment] 2018-04-06 14:59
Fixed with get-abisko-soil-plots-linked.sql

**Closed as completed by nutnetadmin** 2018-04-06 14:59 UTC
Labels: bug
