### ISSUE TITLE
biomass categories sometimes not standardized

### ISSUE THREAD

**Issue by ghost** [nutnetadmin/nutnet-data-tracker#106] opened 2018-07-24 21:14 UTC
bio3<- full-biomass-09-April-2018.csv
bio3$category[bio3$category=='FORB + PHLOX DIFFUSA']<-'FORB'

**Comment by nutnetadmin** [comment] 2018-07-27 21:45
Not a bug: The Borer-Seabloom lab could not decide whether to put _Phlox diffusa_ in the forb category or in the woody (I think?) category, so you can talk to Seabloom about the pros/cons of each category assignment. I'll close this for now but re-open this issue if more come up!

**Closed as completed by nutnetadmin** 2018-07-27 21:45 UTC
Labels: bug, improvement

**Comment by ghost** [comment] 2018-07-30 21:01
Quick comment -> in "full-cover-09-April-2018" PHLOX DIFFUSA is listed as functional_group =FORB. Consider standardizing so Biomass and Cover data sets refer to it as "FORB" or "FORB + PHLOX DIFFUSA" similarly?
